# Localization dictionary for English, Hindi, and Marathi

LOCALIZATION = {
    "English": {
        "title": "FarmGuardian AI",
        "tagline": "An intelligent farming companion that plans, monitors, diagnoses, and protects smallholders throughout the crop lifecycle.",
        "profile": "Farmer Profile",
        "name": "Farmer Name",
        "location": "Farming Location / District",
        "acreage": "Land Size (Acres)",
        "crop": "Active Crop",
        "soil": "Soil Type",
        "lang": "Preferred Language",
        "chat_header": "Farm Consultation Desk",
        "upload_label": "Upload crop image (Leaf / Spot / Pest / Weed)",
        "upload_placeholder": "Choose a photo from your field",
        "chat_placeholder": "Ask crop symptoms, weather plans, mandi rates...",
        "send_btn": "Send to Agentic Network",
        "welcome": "Namaste {name}! How can I assist you with your **{crop}** crop in **{location}** today?",
        "agent_viz": "Agentic Orchestration Visualizer",
        "trajectory": "Reasoning/Agent Trajectory",
        "skills_header": "Dynamic Skills Activation",
        "decision_header": "Agricultural Decision Support",
        "weather_card": "Weather Forecast",
        "market_card": "Mandi Price Watch",
        "economics": "Treatment Economics",
        "explain": "Diagnostic Explainability",
        "weekly": "Interactive Weekly Planner",
        "timeline": "Crop Care Timeline",
        "security": "Security & Archiving Vault",
        "pending_hitl": "Human confirmation required",
        "confirm_btn": "Approve Action",
        "reject_btn": "Reject Action",
        "dashboard_title": "Farm Insights Dashboard",
        "crop_health_card": "Crop Health",
        "weather_outlook_card": "Weather Outlook",
        "market_value_card": "Market Value",
        "next_task_card": "Next Scheduled Task",
        "crop_label": "Crop",
        "rain_prob_label": "Rain Prob",
        "trend_label": "Trend",
        "no_pending_tasks": "No pending tasks",
        "refer_weekly_planner": "Refer to Weekly Planner",
        "quick_demo_header": "⚡ Quick Demo Scenarios (Pre-loaded for Judges)",
        "google_integration_header": "Google Account Integration",
        "google_sync_logs_header": "🗄️ Google Drive & Calendar Sync Logs",
        "google_cal_events": "**Google Calendar Events**",
        "google_drive_docs": "**Google Drive Docs**",
        "info_no_planner_tasks": "No planner tasks generated yet. Start a consultation turn or select a scenario below.",
        "info_google_connected": "Connected to Google: ramesh.kumar@gmail.com",
        "info_google_disconnected": "Google Account status: Disconnected",
        "disconnect_btn": "Disconnect Google Account",
        "connect_btn": "Connect Google Account",
        "link_google_cal": "Please link your Google Account to enable calendar sync.",
        "link_google_drive": "Please link your Google Account to enable drive archiving.",
        "no_cal_synced": "No Calendar events synced yet.",
        "no_drive_synced": "No Drive documents archived yet.",
        "pesticide_reject_msg": "Action Rejected. Planning cancelled.",
        "no_pending_security": "No pending security overrides or approvals. Status secure."
    },
    "Hindi (हिन्दी)": {
        "title": "फार्मगार्जियन एआई",
        "tagline": "एक बुद्धिमान कृषि साथी जो फसल चक्र के दौरान छोटे किसानों की योजना, निगरानी, निदान और सुरक्षा करता है।",
        "profile": "किसान प्रोफ़ाइल",
        "name": "किसान का नाम",
        "location": "कृषि स्थान / जिला",
        "acreage": "भूमि का आकार (एकड़)",
        "crop": "सक्रिय फसल",
        "soil": "मिट्टी का प्रकार",
        "lang": "पसंदीदा भाषा",
        "chat_header": "कृषि परामर्श डेस्क",
        "upload_label": "फसल की छवि अपलोड करें (पत्ता / धब्बा / कीट / खरपतवार)",
        "upload_placeholder": "अपने खेत से एक फोटो चुनें",
        "chat_placeholder": "रोगों, मौसम, उर्वरकों, बाजार की कीमतों या सब्सिडी के बारे में पूछें...",
        "send_btn": "एजेंट नेटवर्क को भेजें",
        "welcome": "नमस्ते {name}! आज मैं आपकी **{location}** में **{crop}** की फसल के लिए किस प्रकार सहायता कर सकता हूँ?",
        "agent_viz": "एजेंट ऑर्केस्ट्रेशन विजुअलाइज़र",
        "trajectory": "एजेंट तर्क/प्रक्षेपवक्र",
        "skills_header": "गतिशील कौशल सक्रियण",
        "decision_header": "कृषि निर्णय सहायता",
        "weather_card": "मौसम पूर्वानुमान",
        "market_card": "मंडी दरें",
        "economics": "उपचार अर्थशास्त्र",
        "explain": "नैदानिक व्याख्या",
        "weekly": "साप्ताहिक योजना",
        "timeline": "फसल देखभाल समयरेखा",
        "security": "सुरक्षा और संग्रह वॉल्ट",
        "pending_hitl": "मानव पुष्टि आवश्यक है",
        "confirm_btn": "कार्रवाई स्वीकृत करें",
        "reject_btn": "कार्रवाई अस्वीकार करें",
        "dashboard_title": "कृषि अंतर्दृष्टि डैशबोर्ड",
        "crop_health_card": "फसल स्वास्थ्य",
        "weather_outlook_card": "मौसम का दृष्टिकोण",
        "market_value_card": "बाजार मूल्य",
        "next_task_card": "अगला निर्धारित कार्य",
        "crop_label": "फसल",
        "rain_prob_label": "बारिश की संभावना",
        "trend_label": "रुझान",
        "no_pending_tasks": "कोई लंबित कार्य नहीं",
        "refer_weekly_planner": "साप्ताहिक योजना देखें",
        "quick_demo_header": "⚡ त्वरित डेमो परिदृश्य (जजों के लिए पूर्व-लोडेड)",
        "google_integration_header": "गूगल खाता एकीकरण",
        "google_sync_logs_header": "🗄️ गूगल ड्राइव और कैलेंडर सिंक लॉग",
        "google_cal_events": "**गूगल कैलेंडर इवेंट**",
        "google_drive_docs": "**गूगल ड्राइव दस्तावेज़**",
        "info_no_planner_tasks": "अभी तक कोई योजना कार्य जनरेट नहीं हुआ है। परामर्श बारी शुरू करें या नीचे एक परिदृश्य चुनें।",
        "info_google_connected": "गूगल से जुड़ा है: ramesh.kumar@gmail.com",
        "info_google_disconnected": "गूगल खाता स्थिति: डिस्कनेक्ट किया गया",
        "disconnect_btn": "गूगल खाता डिस्कनेक्ट करें",
        "connect_btn": "गूगल खाता कनेक्ट करें",
        "link_google_cal": "कैलेंडर सिंक सक्षम करने के लिए कृपया अपना गूगल खाता लिंक करें।",
        "link_google_drive": "ड्राइव संग्रह सक्षम करने के लिए कृपया अपना गूगल खाता लिंक करें।",
        "no_cal_synced": "अभी तक कोई कैलेंडर इवेंट सिंक नहीं हुआ है।",
        "no_drive_synced": "अभी तक कोई ड्राइव दस्तावेज़ संग्रहीत नहीं हुआ है।",
        "pesticide_reject_msg": "कार्रवाई अस्वीकार कर दी गई। योजना रद्द।",
        "no_pending_security": "कोई लंबित सुरक्षा ओवरराइड या स्वीकृति नहीं है। स्थिति सुरक्षित है।"
    },
    "Marathi (मराठी)": {
        "title": "फार्मगार्डियन एआई (FarmGuardian AI)",
        "tagline": "एक बुद्धिमान कृषी सहकारी जो पीक जीवनचक्रादरम्यान लहान शेतकऱ्यांचे नियोजन, निरीक्षण, निदान आणि संरक्षण करतो.",
        "profile": "शेतकरी प्रोफाइल",
        "name": "शेतकऱ्याचे नाव",
        "location": "शेतीचे ठिकाण / जिल्हा",
        "acreage": "जमिनीचा आकार (एकर)",
        "crop": "सक्रिय पीक",
        "soil": "मातीचा प्रकार",
        "lang": "पसंदीदा भाषा",
        "chat_header": "कृषी सल्लागार डेस्क",
        "upload_label": "पिकाचे चित्र अपलोड करा (पान / डाग / कीड / तण)",
        "upload_placeholder": "तुमच्या शेतातून एक फोटो निवडा",
        "chat_placeholder": "रोग, हवामान, खते, बाजारभाव किंवा अनुदानाबद्दल विचारा...",
        "send_btn": "एजंट नेटवर्कवर पाठवा",
        "welcome": "नमस्कार {name}! आज मी तुम्हाला **{location}** मधील तुमच्या **{crop}** पिकासाठी कशी मदत करू शकतो?",
        "agent_viz": "एजंट ऑर्केस्ट्रेशन व्हिज्युअलायझर",
        "trajectory": "एजंट तर्क/प्रक्षेपवक्र",
        "skills_header": "डायनॅमिक कौशल्ये सक्रियकरण",
        "decision_header": "कृषी निर्णय समर्थन",
        "weather_card": "हवामान अंदाज",
        "market_card": "बाजारभाव",
        "economics": "उपचार अर्थशास्त्र",
        "explain": "निदान स्पष्टीकरण",
        "weekly": "परस्पर साप्ताहिक नियोजक",
        "timeline": "पीक काळजी टाइमलाइन",
        "security": "सुरक्षा आणि संग्रहण वॉल्ट",
        "pending_hitl": "मानवी मंजुरी आवश्यक आहे",
        "confirm_btn": "क्रिया मंजूर करा",
        "reject_btn": "क्रिया नाकारा",
        "dashboard_title": "कृषी अंतर्दृष्टी डॅशबोर्ड",
        "crop_health_card": "पीक आरोग्य",
        "weather_outlook_card": "हवामान अंदाज",
        "market_value_card": "बाजार मूल्य",
        "next_task_card": "पुढील नियोजित कार्य",
        "crop_label": "पीक",
        "rain_prob_label": "पावसाची शक्यता",
        "trend_label": "कल",
        "no_pending_tasks": "कोणतीही प्रलंबित कामे नाहीत",
        "refer_weekly_planner": "साप्ताहिक नियोजक पहा",
        "quick_demo_header": "⚡ द्रुत डेमो परिस्थिती (परीक्षकांसाठी पूर्व-लोड केलेले)",
        "google_integration_header": "गुगल खाते एकत्रीकरण",
        "google_sync_logs_header": "🗄️ गुगल ड्राइव्ह आणि कॅलेंडर सिंक लॉग",
        "google_cal_events": "**गुगल कॅलेंडर इव्हेंट्स**",
        "google_drive_docs": "**गुगल ड्राइव्ह दस्तऐवज**",
        "info_no_planner_tasks": "अद्याप कोणतीही नियोजक कार्ये तयार केलेली नाहीत. सल्लामसलत सुरू करा किंवा खालील पर्याय निवडा.",
        "info_google_connected": "गुगलशी जोडले गेले: ramesh.kumar@gmail.com",
        "info_google_disconnected": "गुगल खाते स्थिती: डिस्कनेक्ट केले",
        "disconnect_btn": "गुगल खाते डिस्कनेक्ट करा",
        "connect_btn": "गुगल खाते कनेक्ट करा",
        "link_google_cal": "कॅलेंडर सिंक सक्षम करण्यासाठी कृपया तुमचे गुगल खाते लिंक करा.",
        "link_google_drive": "ड्राइव्ह संग्रहण सक्षम करण्यासाठी कृपया तुमचे गुगल खाते लिंक करा.",
        "no_cal_synced": "अद्याप कोणतेही कॅलेंडर इव्हेंट सिंक केलेले नाहीत.",
        "no_drive_synced": "अद्याप कोणतेही ड्राइव्ह दस्तऐवज संग्रहित केलेले नाहीत.",
        "pesticide_reject_msg": "क्रिया नाकारली. नियोजन रद्द केले.",
        "no_pending_security": "कोणतीही प्रलंबित सुरक्षा मंजुरी नाही. स्थिती सुरक्षित आहे."
    }
}


def get_translations(lang: str) -> dict[str, str]:
    """Return localized dictionary for selected language."""
    return LOCALIZATION.get(lang, LOCALIZATION["English"])
