# Localization dictionary for English, Hindi, and Marathi

LOCALIZATION = {
    "English": {
        "title": "FarmGuardian AI",
        "tagline": "An intelligent farming companion that plans, monitors, diagnoses, and protects smallholders throughout the crop lifecycle.",
        "profile": "Farmer Profile",
        "name": "Farmer Name",
        "location": "Farming Location / District",
        "acreage": "Land Size (Acres)",
        "crop": "Active Crop",
        "soil": "Soil Type",
        "lang": "Preferred Language",
        "chat_header": "Farm Consultation Desk",
        "upload_label": "Upload crop image (Leaf / Spot / Pest / Weed)",
        "upload_placeholder": "Choose a photo from your field",
        "chat_placeholder": "Ask crop symptoms, weather plans, mandi rates...",
        "send_btn": "Send to Agentic Network",
        "welcome": "Namaste {name}! How can I assist you with your **{crop}** crop in **{location}** today?",
        "agent_viz": "Agentic Orchestration Visualizer",
        "trajectory": "Reasoning/Agent Trajectory",
        "skills_header": "Dynamic Skills Activation",
        "decision_header": "Agricultural Decision Support",
        "weather_card": "Weather Forecast",
        "market_card": "Mandi Price Watch",
        "economics": "Treatment Economics",
        "explain": "Diagnostic Explainability",
        "weekly": "Interactive Weekly Planner",
        "timeline": "Crop Care Timeline",
        "security": "Security & Archiving Vault",
        "pending_hitl": "Human confirmation required",
        "confirm_btn": "Approve Action",
        "reject_btn": "Reject Action"
    },
    "Hindi (हिन्दी)": {
        "title": "फार्मगार्जियन एआई",
        "tagline": "एक बुद्धिमान कृषि साथी जो फसल चक्र के दौरान छोटे किसानों की योजना, निगरानी, निदान और सुरक्षा करता है।",
        "profile": "किसान प्रोफ़ाइल",
        "name": "किसान का नाम",
        "location": "कृषि स्थान / जिला",
        "acreage": "भूमि का आकार (एकड़)",
        "crop": "सक्रिय फसल",
        "soil": "मिट्टी का प्रकार",
        "lang": "पसंदीदा भाषा",
        "chat_header": "कृषि परामर्श डेस्क",
        "upload_label": "फसल की छवि अपलोड करें (पत्ता / धब्बा / कीट / खरपतवार)",
        "upload_placeholder": "अपने खेत से एक फोटो चुनें",
        "chat_placeholder": "रोगों, मौसम, उर्वरकों, बाजार की कीमतों या सब्सिडी के बारे में पूछें...",
        "send_btn": "एजेंट नेटवर्क को भेजें",
        "welcome": "नमस्ते {name}! आज मैं आपकी **{location}** में **{crop}** की फसल के लिए किस प्रकार सहायता कर सकता हूँ?",
        "agent_viz": "एजेंट ऑर्केस्ट्रेशन विजुअलाइज़र",
        "trajectory": "एजेंट तर्क/प्रक्षेपवक्र",
        "skills_header": "गतिशील कौशल सक्रियण",
        "decision_header": "कृषि निर्णय सहायता",
        "weather_card": "मौसम पूर्वानुमान",
        "market_card": "मंडी दरें",
        "economics": "उपचार अर्थशास्त्र",
        "explain": "नैदानिक व्याख्या",
        "weekly": "इंटरैक्टिव साप्ताहिक योजना",
        "timeline": "फसल देखभाल समयरेखा",
        "security": "सुरक्षा और संग्रह वॉल्ट",
        "pending_hitl": "मानव पुष्टि आवश्यक है",
        "confirm_btn": "कार्रवाई स्वीकृत करें",
        "reject_btn": "कार्रवाई अस्वीकार करें"
    },
    "Marathi (मराठी)": {
        "title": "फार्मगार्डियन एआई (FarmGuardian AI)",
        "tagline": "एक बुद्धिमान कृषी सहकारी जो पीक जीवनचक्रादरम्यान लहान शेतकऱ्यांचे नियोजन, निरीक्षण, निदान आणि संरक्षण करतो.",
        "profile": "शेतकरी प्रोफाइल",
        "name": "शेतकऱ्याचे नाव",
        "location": "शेतीचे ठिकाण / जिल्हा",
        "acreage": "जमिनीचा आकार (एकर)",
        "crop": "सक्रिय पीक",
        "soil": "मातीचा प्रकार",
        "lang": "पसंदीदा भाषा",
        "chat_header": "कृषी सल्लागार डेस्क",
        "upload_label": "पिकाचे चित्र अपलोड करा (पान / डाग / कीड / तण)",
        "upload_placeholder": "तुमच्या शेतातून एक फोटो निवडा",
        "chat_placeholder": "रोग, हवामान, खते, बाजारभाव किंवा अनुदानाबद्दल विचारा...",
        "send_btn": "एजंट नेटवर्कवर पाठवा",
        "welcome": "नमस्कार {name}! आज मी तुम्हाला **{location}** मधील तुमच्या **{crop}** पिकासाठी कशी मदत करू शकतो?",
        "agent_viz": "एजंट ऑर्केस्ट्रेशन व्हिज्युअलायझर",
        "trajectory": "एजंट तर्क/प्रक्षेपवक्र",
        "skills_header": "डायनॅमिक कौशल्ये सक्रियकरण",
        "decision_header": "कृषी निर्णय समर्थन",
        "weather_card": "हवामान अंदाज",
        "market_card": "बाजारभाव",
        "economics": "उपचार अर्थशास्त्र",
        "explain": "निदान स्पष्टीकरण",
        "weekly": "परस्पर साप्ताहिक नियोजक",
        "timeline": "पीक काळजी टाइमलाइन",
        "security": "सुरक्षा आणि संग्रहण वॉल्ट",
        "pending_hitl": "मानवी मंजुरी आवश्यक आहे",
        "confirm_btn": "क्रिया मंजूर करा",
        "reject_btn": "क्रिया नाकारा"
    }
}


def get_translations(lang: str) -> dict[str, str]:
    """Return localized dictionary for selected language."""
    return LOCALIZATION.get(lang, LOCALIZATION["English"])
